# Generated by Django 4.1.7 on 2024-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_folder_unique_folder_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_folder_on_home_page'),
        ),
    ]
