# Generated by Django 4.1.7 on 2024-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_folder_unique_folder_on_home_page'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_on_home_page',
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('folder', None)), fields=('name', 'user'), name='unique_folder_on_home_page'),
        ),
    ]
